apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  database-password: "#{Octopub.Yaml.Database.Server.Password}"
  database-user: "#{Octopub.Yaml.Database.Server.User}"